# ============================================================
# agents/evaluator_agent.py
# This node checks whether the answer generated by the selected
# agent is good enough for the user's question.
#
# It uses a FAST routing/evaluation LLM:
# - If the answer is good -> PASS
# - If the answer is weak -> RETRY
#
# On RETRY, it sends feedback back into shared state so the router
# can try again with improvement guidance.
#
# Retry is limited to 2 times to avoid infinite loops.
# If max retries is reached and the answer is still weak,
# Human-in-the-Loop (HITL) is triggered.
# ============================================================

from agents.shared import AgentState, routing_evaluation_llm
from langchain_core.prompts import PromptTemplate

EVAL_PROMPT = PromptTemplate.from_file("prompts/evaluator_prompt.txt")

MAX_RETRIES = 2

# Extract evaluator decision, reason and feedback from the evaluator response
def _parse_eval_output(raw_text: str) -> tuple[str, str, str]:
    text = str(raw_text).strip()
    text_lower = text.lower()

    decision = "pass"
    reason = "The answer is acceptable."
    retry_instruction = "none"

    for line in text.splitlines():
        lower_line = line.lower().strip()

        if lower_line.startswith("decision:"):
            value = line.split(":", 1)[1].strip().lower()
            if value in ("pass", "retry"):
                decision = value

        elif lower_line.startswith("reason:"):
            extracted = line.split(":", 1)[1].strip()
            if extracted:
                reason = extracted

        elif lower_line.startswith("retry_instruction:"):
            extracted = line.split(":", 1)[1].strip()
            if extracted:
                retry_instruction = extracted

    if "decision:" not in text_lower:
        if "retry" in text_lower:
            decision = "retry"
        elif "pass" in text_lower:
            decision = "pass"

    if decision == "pass":
        retry_instruction = "none"

    if not reason:
        reason = "The answer is acceptable."

    if not retry_instruction:
        retry_instruction = "none"

    return decision, reason, retry_instruction

def evaluator_node(state: AgentState) -> AgentState:
    original_question = state.get("question", "")
    standalone_question = state.get("standalone_question", "") or original_question
    answer = state.get("answer", "")
    agent_used = state.get("agent_used", "")
    retry_count = state.get("retry_count", 0)

    existing_trace = list(state.get("execution_trace", []))

    node_steps = [
        {
            "trace_id": f"evaluator-check-{retry_count}",
            "icon": "⚖️",
            "step": "Evaluator → Checking answer quality",
            "detail": f"Reviewing the answer produced by the {agent_used} agent."
        }
    ]

    print(f"EVALUATOR: checking answer from agent={agent_used}, retry_count={retry_count}")

    eval_prompt = EVAL_PROMPT.format(
        original_question=original_question,
        question=standalone_question,
        answer=answer,
        agent_used=agent_used
    )

    # Use the fast routing/evaluation model here because evaluation is
    # a short classification-style task and does not need the heavier
    # generation model.
    raw_eval = routing_evaluation_llm.invoke(eval_prompt)
    print(f"EVALUATOR RAW OUTPUT: {raw_eval}")

    raw_text = str(raw_eval)
    decision, reason, retry_instruction = _parse_eval_output(raw_text)
    print(
        f"EVALUATOR PARSED -> decision={decision}, "
        f"reason={reason}, retry_instruction={retry_instruction}"
    )

    if decision == "retry":
        if retry_count >= MAX_RETRIES:
            print("EVALUATOR: max retries reached, triggering HITL")
            node_steps.append({
                "trace_id": f"evaluator-hitl-{retry_count}",
                "icon": "🧑‍⚖️",
                "step": "Evaluator → Human-in-the-Loop required",
                "detail": reason or "Retry limit reached. User review is required."
            })

            return {
                **state,
                "evaluation_result": "pass",
                "evaluator_feedback": reason,
                "evaluator_reason": reason,
                "retry_instruction": "none",
                "hitl_needed": True,
                "hitl_reason": reason or "Retry limit reached. User review is required.",
                "execution_trace": existing_trace + node_steps,
                "new_trace_steps": node_steps
            }

        new_retry_count = retry_count + 1
        node_steps.append({
            "trace_id": f"evaluator-retry-{new_retry_count}",
            "icon": "🔄",
            "step": f"Evaluator → Answer feels weak, retrying ({new_retry_count}/{MAX_RETRIES})",
            "detail": reason
        })

        return {
            **state,
            "evaluation_result": "retry",
            "evaluator_feedback": reason,
            "evaluator_reason": reason,
            "retry_instruction": retry_instruction or "Improve answer quality.",
            "retry_count": new_retry_count,
            "hitl_needed": False,
            "hitl_reason": "",
            "execution_trace": existing_trace + node_steps,
            "new_trace_steps": node_steps
        }

    node_steps.append({
        "trace_id": f"evaluator-pass-{retry_count}",
        "icon": "✅",
        "step": "Evaluator → Answer accepted",
        "detail": reason
    })

    return {
        **state,
        "evaluation_result": "pass",
        "evaluator_feedback": reason,
        "evaluator_reason": reason,
        "retry_instruction": "none",
        "hitl_needed": False,
        "hitl_reason": "",
        "execution_trace": existing_trace + node_steps,
        "new_trace_steps": node_steps
    }